# Generated by Django 4.1.7 on 2023-05-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogba', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
