# Generated by Django 4.1.7 on 2023-05-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogba', '0008_pogba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
    ]
