# Generated by Django 4.1.7 on 2023-05-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogba', '0009_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='icmphdr',
        ),
    ]
