# Generated by Django 4.1.7 on 2023-05-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogba', '0013_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
