# Generated by Django 4.1.7 on 2023-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogba', '0015_tcphdr_udphdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='icmphdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.PositiveIntegerField()),
                ('cid', models.PositiveIntegerField()),
                ('icmp_type', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'icmphdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='iphdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.PositiveIntegerField()),
                ('cid', models.PositiveIntegerField()),
                ('ip_src', models.PositiveIntegerField()),
                ('ip_dst', models.PositiveIntegerField()),
                ('ip_ttl', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'iphdr',
                'managed': False,
            },
        ),
    ]
