# Generated by Django 4.1.7 on 2023-05-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogba', '0016_icmphdr_iphdr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='icmphdr',
        ),
        migrations.DeleteModel(
            name='iphdr',
        ),
        migrations.DeleteModel(
            name='tcphdr',
        ),
        migrations.DeleteModel(
            name='udphdr',
        ),
    ]
